### ISSUE TITLE
Jenkins X Boot - Storage

### ISSUE THREAD

**Issue by GLStephen** [jenkins-x/jx-docs#2370]
On new or fresh environments gsutil may not exist and jenkinsx can't verify the bucket. Need to install it or say it's required.

**Comment by sharepointoscar** [comment]
For our edification:  Can you put details on your scenario?

Cloud

How you installed JX

Version of JX (paste output from `jx version`

Lastly, what were you executing when you got that message? 

Thanks @GLStephen

**Comment by GLStephen** [comment]
GCE
jx boot

```
storage:
  backup:
    enabled: true
    url: gs://bucket
  logs:
    enabled: true
    url: gs://bucket
  reports:
    enabled: true
    url: gs://bucket
  repository:
    enabled: true
    url: gs://bucket
```

Executing jx boot

NAME               VERSION
jx                 2.0.1142
Kubernetes cluster v1.13.11-gke.14
kubectl            v1.13.2
helm client        Client: v2.12.2+g7d2b0c7
git                2.17.1
Operating System   Ubuntu 18.04.2 LTS

The salient element is that gcloud doesn't always install gsutil. jx boot asssumes it is installed.
