### ISSUE TITLE
Usage of terraform flag in install requiremtents

### ISSUE THREAD

**Issue by sharepointoscar** [jenkins-x/jx-docs#2402]
Are we saying the user should indicate `terraform:true` as follows?  Just to clarfify....

Or please indicate where this should be specified?

```yaml
clusterConfig:
    provider: aws
    terraform: true
```
