### ISSUE TITLE
document manual steps for TLS 

### ISSUE THREAD

**Issue by rawlingsj** [jenkins-x/jx-docs#259]
including having to regenerate external URL service annotations

**Comment by rawlingsj** [comment]
this should also include suggestions for running certmanager and the custom resource definitions folks might need, i.e.

```
helm install --name cert-manager --namespace kube-system stable/cert-manager --set rbac.create=false --set ingressShim.extraArgs='{--default-issuer-name=letsencrypt-staging,--default-issuer-kind=ClusterIssuer}'

apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    # The ACME server URL
    server: https://acme-v01.api.letsencrypt.org/directory
    # Email address used for ACME registration
    email: foo@acme.com
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt-prod
    # Enable the HTTP-01 challenge provider
    http01: {}

apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    # The ACME server URL
    server: https://acme-staging.api.letsencrypt.org/directory
    # Email address used for ACME registration
    email: foo@acme.com
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt-staging
    # Enable the HTTP-01 challenge provider
    http01: {}

apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: jenkinsxio-cert
spec:
  secretName: tls-jx-jenkinsxio
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: foo.jenkins-x.io
  dnsNames:
  - foo.jenkins-x.io
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
      - foo.jenkins-x.io
```

**Comment by deyceg** [comment]
thanks @rawlingsj 

Steps to reproduce:

1. Install cert-manager

`helm install stable/cert-manager --name letsencrypt --namespace kube-system --set extraArgs="{-v=5}",ingressShim.defaultIssuerName=letsencrypt-staging,ingressShim.defaultIssuerKind=ClusterIssuer`

2. Create `ClusterIssuer`

```
apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    # The ACME server URL
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    # Email address used for ACME registration
    email: admin@domain.com
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt-staging
    # Enable the HTTP-01 challenge provider
    http01: {}
```

3. Create jx cert

```
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: jx-cert
spec:
  secretName: tls-jx
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  commonName: jenkins.jx.yourdomain.com
  dnsNames:
    - chartmuseum.jx.yourdomain.com
    - docker-registry.jx.yourdomain.com
    - monocular.jx.yourdomain.com
    - nexus.jx.yourdomain.com
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
      - chartmuseum.jx.yourdomain.com
      - docker-registry.jx.yourdomain.com
      - jenkins.jx.yourdomain.com
      - monocular.jx.yourdomain.com
      - nexus.jx.yourdomain.com
```

4. Reconfigure Jenkins `Service` annotation

`fabric8.io/exposeUrl: http://jenkins.jx.yourdomain.com` -> `fabric8.io/exposeUrl: https://jenkins.jx.yourdomain.com`
