### ISSUE TITLE
Pin version of chabad360/htmlproofer

### ISSUE THREAD

**Issue by hferentschik** [jenkins-x/jx-docs#2591]
As part of the pull requests builds we are using chabad360/htmlproofer to link and sytnax check the generated HTML. 

This is the config in `jenkins-x.yml`:

```yaml
          - image: chabad360/htmlproofer:latest
            name: htmlproofer
            command: htmlproofer
            args:
              - ./tmp-website
              - --allow-hash-href
              - --disable-external
              - --check-html
              - --checks-to-ignore ScriptCheck
              - --empty-alt-ignore
              - --file-ignore /.*apidocs.*/,/.*\/zh.*/,/.*\/es.*/,/.*\/docs\/reference\/api.*/,/.*\/docs\/reference\/config.*/,/.*\/community\/events.*/
```

The problem is that we use the latest image which can change the build behaviour when it gets updated. During a previous change in the image additional checks got enabled which made all pull request preview builds fail. The image version should be pinned. Unfortunately, there are no tag for this image, just latest. 

A solution might be to take the current latest image and add it to the Jenkins X repository. Alternatively, we could try to "fix" it upstream by asking the maintainer of chabad360/htmlproofer to publish tags.
