### ISSUE TITLE
Add Gitea configuration in jx-requirements.yaml 

### ISSUE THREAD

**Issue by nbon12** [jenkins-x/jx-docs#3693]
I couldn't find gitea in the list of supported git providers: https://jenkins-x.io/v3/admin/setup/config/git/
Is gitea supported? If so, what is the proper yaml configuration to use for gitea in the jx-requirements.yaml?

For example:

```
cluster:
  provider: ?
  gitKind: ?
...
```
